[package]
name        = "carrier"
version     = "0.8.0"
authors     = ["Arvid E. Picciani <arvid@devguard.io>"]
license     = "MIT"
description = "carrier is a generic secure message system for IoT"
homepage    = "https://devguard.io"

[dependencies]
bs58                = "0.2.2"
byteorder           = "1.3.1"
clear_on_drop       = "0.2.3"
crc8                = "0.1.1"
ed25519-dalek       = "1.0.0-pre.1"
log                 = { version = "0.4.6", features = ["release_max_level_debug"] }
sha2                = "0.8.0"
subtle              = "2.0.0"
x25519-dalek        = { version = "0.4.4", default-features = false, features = ["std", "u64_backend"] }
rand                = "0.6.4"
prost               = "0.4.0"
prost-derive        = "0.4.0"
bytes               = "0.4.11"
hpack               = "0.3.0"

osaka               = "0.2.5"
osaka-dns           = "0.2.5"

#osaka       = {path = "../../osaka/osaka"}
#osaka-dns   = {path = "../../osaka/osaka-dns"}

mtdparts            = "0.2.0"
mio                 = "0.6.16"
mio-extras          = "2.0.5"
dirs                = "1.0.4"
toml                = "0.4.10"
serde               = "1.0.85"
serde_derive        = "1.0.85"
interfaces          = "0.0.4"

#main
which               = "2.0.1"
tinylogger          = "0.1.0"
axon                = "0.2.0"
clap                = "2.32.0"
num_cpus            = "1.9.0"
wait-timeout        = "0.2.0"


#pty
nix                 = "0.13.0"
#for TIOCSCTTY
libc                = "0.2.48"


[dependencies.snow]
version             = "0.4.2"
default-features    = false
features            = ["hacl-star-resolver"]


[lib]
name = "carrier"
path = "src/lib.rs"

[[bin]]
name = "carrier"
path = "src/main.rs"

#[patch.crates-io]
#hacl-star-sys   = {git = "https://github.com/quininer/rust-hacl-star.git", branch="fix32"}

[build-dependencies]
prost-build = "0.4.0"

[profile.release]
lto = true
opt-level = "z"
panic = 'abort'
incremental = false

